#!/usr/bin/env python3
import ast
import re
import tempfile
from pathlib import Path

import RenPyAIPatcher as core

_CJK_FONT_HINTS = (
    "noto", "cjk", "sourcehan", "source_han", "source-han", "nanum",
    "malgun", "korean", "hangul", "pretendard", "spoqa", "unfonts", "unfont",
)


def decode_rpy_text(raw, quote='"'):
    """Turn a source-level Ren'Py quoted string into the runtime text key.

    The old extractor kept escape sequences literally. That makes a generated
    translate-strings `old` key fail to match dialogue containing \n, escaped
    quotes, unicode escapes, etc. Ren'Py string syntax is close enough to Python
    for ordinary quoted dialogue; use literal_eval and a conservative fallback.
    """
    literal = quote + raw + quote
    try:
        value = ast.literal_eval(literal)
        if isinstance(value, str):
            return value
    except Exception:
        pass

    # Conservative fallback: decode only escapes that are unambiguous in Ren'Py
    # dialogue while leaving unknown backslash sequences untouched.
    def repl(match):
        token = match.group(0)
        table = {
            r"\\": "\\",
            r"\n": "\n",
            r"\r": "\r",
            r"\t": "\t",
            r'\"': '"',
            r"\'": "'",
        }
        if token in table:
            return table[token]
        if token.startswith(r"\u") and len(token) == 6:
            try:
                return chr(int(token[2:], 16))
            except Exception:
                return token
        if token.startswith(r"\U") and len(token) == 10:
            try:
                return chr(int(token[2:], 16))
            except Exception:
                return token
        return token

    return re.sub(r"\\(?:\\|n|r|t|\"|'|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})", repl, raw)


def extract_strings_compat(path):
    """Compatibility extractor using runtime-equivalent string values."""
    out, seen = [], set()
    path = Path(path)
    for no, line in enumerate(path.read_text("utf-8", errors="replace").splitlines(), 1):
        for match in core.STRING_RE.finditer(line):
            raw = match.group("text")
            value = decode_rpy_text(raw, match.group("quote"))
            if core.looks_translatable(line, value) and value not in seen:
                seen.add(value)
                out.append((no, value))
    return out


def find_cjk_font(game_dir, max_files=5000):
    """Find an already-bundled CJK/Korean font without redistributing fonts."""
    game_dir = Path(game_dir)
    checked = 0
    candidates = []
    try:
        for path in game_dir.rglob("*"):
            checked += 1
            if checked > max_files:
                break
            if not path.is_file() or path.suffix.lower() not in {".ttf", ".otf", ".ttc"}:
                continue
            name = path.name.lower()
            score = sum(1 for hint in _CJK_FONT_HINTS if hint in name)
            if score:
                try:
                    rel = path.relative_to(game_dir).as_posix()
                except Exception:
                    rel = path.name
                candidates.append((score, rel))
    except Exception:
        return None
    if not candidates:
        return None
    candidates.sort(key=lambda row: (-row[0], len(row[1])))
    return candidates[0][1]


def write_language_compat(game_dir, target_dir):
    """Activate language early and optionally switch to a bundled Korean font."""
    game_dir = Path(game_dir)
    loader = game_dir / "renpytools_language.rpy"
    font = find_cjk_font(game_dir) if target_dir == "korean" else None

    lines = [
        "# Generated by RenPy Tools v0.4.9",
        "# Set the startup language before normal game init completes.",
        f"define config.language = {target_dir!r}",
        "",
    ]
    if target_dir == "korean":
        lines.extend([
            "translate korean python:",
            "    try:",
            "        gui.language = 'korean-with-spaces'",
            "    except Exception:",
            "        pass",
        ])
        if font:
            lines.extend([
                "    try:",
                f"        gui.text_font = {font!r}",
                f"        gui.name_text_font = {font!r}",
                f"        gui.interface_text_font = {font!r}",
                f"        gui.system_font = {font!r}",
                "    except Exception:",
                "        pass",
            ])
        lines.append("")

    loader.write_text("\n".join(lines), encoding="utf-8")
    return loader, font


_ORIGINAL_APPLY = core.PatcherApp.apply_patch_to_game


def apply_patch_compat(self, patch_root, game_dir, target_dir):
    destination, backup = _ORIGINAL_APPLY(self, patch_root, game_dir, target_dir)
    # Replace the late v0.3.7 loader with the early/official-style v0.4.9 loader.
    write_language_compat(Path(game_dir), target_dir)
    return destination, backup


def install_v049_compat():
    core.extract_strings = extract_strings_compat
    core.PatcherApp.apply_patch_to_game = apply_patch_compat
    return True


def run_v049_self_test():
    try:
        assert decode_rpy_text(r"Hello\nWorld") == "Hello\nWorld"
        assert decode_rpy_text(r"She said: \"Hi\"") == 'She said: "Hi"'
        assert decode_rpy_text(r"\u4f60\u597d") == "你好"

        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            script = root / "script.rpy"
            script.write_text('label start:\n    "Hello\\nWorld"\n    "\\u4f60\\u597d"\n', encoding="utf-8")
            rows = extract_strings_compat(script)
            values = [x[1] for x in rows]
            assert "Hello\nWorld" in values
            assert "你好" in values

            game = root / "game"
            game.mkdir()
            fonts = game / "fonts"
            fonts.mkdir()
            (fonts / "NotoSansCJKkr-Regular.ttf").write_bytes(b"not-a-real-font-selftest")
            loader, font = write_language_compat(game, "korean")
            text = loader.read_text(encoding="utf-8")
            assert "define config.language = 'korean'" in text
            assert "korean-with-spaces" in text
            assert font == "fonts/NotoSansCJKkr-Regular.ttf"
        return 0
    except Exception as exc:
        try:
            Path("RenPyTools-v049-selftest-error.txt").write_text(repr(exc), encoding="utf-8")
        except Exception:
            pass
        return 1
