#!/usr/bin/env python3
import shutil
import tempfile
import time
from pathlib import Path

import RenPyAIPatcher as core

_INSTALLED = False


def backup_root_for_game(game_dir):
    game_dir = Path(game_dir)
    return game_dir.parent / "_RenPyTools_Backup"


def migrate_legacy_backup(game_dir):
    """Move old backups out of game/ so Ren'Py cannot compile/execute their .rpy files."""
    game_dir = Path(game_dir)
    legacy = game_dir / "_RenPyTools_Backup"
    if not legacy.exists():
        return None

    outside = backup_root_for_game(game_dir)
    outside.mkdir(parents=True, exist_ok=True)
    stamp = time.strftime("%Y%m%d_%H%M%S")
    dest = outside / f"legacy_inside_game_{stamp}"
    n = 1
    while dest.exists():
        dest = outside / f"legacy_inside_game_{stamp}_{n}"
        n += 1

    try:
        shutil.move(str(legacy), str(dest))
    except Exception:
        shutil.copytree(legacy, dest)
        shutil.rmtree(legacy)
    return dest


def apply_patch_to_game_safe(self, patch_root, game_dir, target_dir):
    game_dir = Path(game_dir)
    if game_dir.name.lower() != "game" or not game_dir.is_dir():
        raise RuntimeError("자동 적용 대상 game 폴더를 찾지 못했습니다.")

    # Older versions stored live .rpy backups under game/_RenPyTools_Backup.
    # Ren'Py recursively scans scripts under game/, so those backups were loaded
    # as real translations and caused duplicate `old` translation exceptions.
    migrate_legacy_backup(game_dir)

    destination = game_dir / "tl" / target_dir
    backup = None
    stamp = time.strftime("%Y%m%d_%H%M%S")
    backup_base = backup_root_for_game(game_dir)

    if destination.exists() and any(destination.rglob("*")):
        backup = backup_base / f"{target_dir}_{stamp}"
        backup.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(destination, backup)
        shutil.rmtree(destination)

    destination.mkdir(parents=True, exist_ok=True)
    shutil.copytree(patch_root, destination, dirs_exist_ok=True)

    language_loader = game_dir / "renpytools_language.rpy"
    if language_loader.exists():
        backup_base.mkdir(parents=True, exist_ok=True)
        loader_backup = backup_base / f"renpytools_language_{stamp}.rpy"
        shutil.copy2(language_loader, loader_backup)

    language_loader.write_text(
        "# Generated by RenPy Tools v0.5.13\n"
        "# Activates the language installed by RenPy Tools.\n"
        f"define config.language = {target_dir!r}\n"
        + (
            "\ntranslate korean python:\n"
            "    try:\n"
            "        gui.language = 'korean-with-spaces'\n"
            "    except Exception:\n"
            "        pass\n"
            if target_dir == "korean" else ""
        ),
        encoding="utf-8",
    )
    return destination, backup


def install_v0513_backup_safety():
    global _INSTALLED
    core.PatcherApp.apply_patch_to_game = apply_patch_to_game_safe
    _INSTALLED = True
    return True


def run_v0513_self_test():
    try:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td) / "Demo"
            game = root / "game"
            old_tl = game / "tl" / "korean"
            old_tl.mkdir(parents=True)
            (old_tl / "old.rpy").write_text("translate korean strings:\n", encoding="utf-8")

            legacy = game / "_RenPyTools_Backup" / "korean_old"
            legacy.mkdir(parents=True)
            (legacy / "renpytools_strings.rpy").write_text("translate korean strings:\n", encoding="utf-8")

            patch = Path(td) / "patch"
            patch.mkdir()
            (patch / "new.rpy").write_text("translate korean strings:\n", encoding="utf-8")

            class Dummy:
                pass

            dest, backup = apply_patch_to_game_safe(Dummy(), patch, game, "korean")
            assert dest == game / "tl" / "korean"
            assert (dest / "new.rpy").is_file()
            assert backup is not None and backup.is_dir()
            assert backup.parent == root / "_RenPyTools_Backup"
            assert not (game / "_RenPyTools_Backup").exists()
            migrated = list((root / "_RenPyTools_Backup").glob("legacy_inside_game_*"))
            assert migrated and (migrated[0] / "korean_old" / "renpytools_strings.rpy").is_file()

            install_v0513_backup_safety()
            assert core.PatcherApp.apply_patch_to_game is apply_patch_to_game_safe
        return 0
    except Exception as exc:
        try:
            Path("RenPyTools-v0513-selftest-error.txt").write_text(repr(exc), encoding="utf-8")
        except Exception:
            pass
        return 1
