#!/usr/bin/env python3
import re
import shutil
import sys
import tempfile
from pathlib import Path

import RenPyAIPatcher as core
import v048_master_hq as master_hq
from v049_compat import decode_rpy_text

BUNDLED_FONT_DIR = "bundled_fonts"
BUNDLED_FONT_NAME = "NotoSansKR.ttf"
BUNDLED_LICENSE_NAME = "NotoSansKR-OFL.txt"
PATCH_FONT_DIR = "renpytools_fonts"
FONT_OVERRIDE_FILE = "renpytools_font.rpy"

_INSTALLED = False
_PREVIOUS_APPLY = None


def _bundled_path(name):
    candidates = []
    meipass = getattr(sys, "_MEIPASS", None)
    if meipass:
        candidates.append(Path(meipass) / BUNDLED_FONT_DIR / name)
    candidates.append(Path(__file__).resolve().parent / BUNDLED_FONT_DIR / name)
    candidates.append(Path.cwd() / BUNDLED_FONT_DIR / name)
    return next((p for p in candidates if p.is_file()), None)


def _short_text_context(line):
    """Allow short human-facing strings without reopening obvious technical literals."""
    s = line.strip()
    lower = s.lower()
    if not s or s.startswith("#"):
        return False
    if re.search(r"\b_+\s*\(", s):
        return True
    if re.match(r"^(?:textbutton|label|text)\s+[\"']", s, re.I):
        return True
    # Menu choice / narrator line: "Yes": or "Hello"
    if re.match(r"^[\"']", s) and (
        re.search(r"[\"']\s*:\s*(?:#.*)?$", s)
        or re.search(r"[\"']\s*(?:#.*)?$", s)
    ):
        return True
    # Character dialogue: e "Yes".
    if re.match(r"^[A-Za-z_][A-Za-z0-9_.]*\s+[\"']", s):
        prefix = re.split(r"[\"']", s, maxsplit=1)[0]
        if "=" not in prefix:
            return True
    if any(token in lower for token in (
        "config.", "gui.", "style.", "define ", "default ", "font",
        "image ", "audio", "music", "sound",
    )):
        return False
    return False


def looks_translatable_v052(line, text):
    if core.looks_translatable(line, text):
        return True
    value = str(text).strip()
    if not value:
        return False
    # v0.3.x treated every single-token ASCII string as technical. That drops
    # real menu/dialogue such as Yes, No, Save, Back, Hello, etc.
    if re.fullmatch(r"[A-Za-z][A-Za-z0-9'!?-]*", value) and _short_text_context(line):
        return True
    return False


def iter_extract_strings_stream_v052(path):
    path = Path(path)
    seen = set()
    with path.open("r", encoding="utf-8", errors="replace") as fp:
        for no, line in enumerate(fp, 1):
            for match in core.STRING_RE.finditer(line):
                raw = match.group("text")
                value = decode_rpy_text(raw, match.group("quote"))
                if looks_translatable_v052(line, value) and value not in seen:
                    seen.add(value)
                    yield no, value


def extract_strings_v052(path):
    return list(iter_extract_strings_stream_v052(path))


def _font_override_text(target_dir="korean"):
    font = f"tl/{target_dir}/{PATCH_FONT_DIR}/{BUNDLED_FONT_NAME}"
    styles = (
        "default", "say_dialogue", "say_label", "input", "button_text",
        "choice_button_text", "quick_button_text", "navigation_button_text",
        "game_menu_label", "game_menu_navigation_button_text", "pref_label",
        "pref_button_text", "slot_button_text", "file_slot_button_text",
        "confirm_prompt", "confirm_button_text", "notify_text",
    )
    return (
        "# Generated by RenPy Tools v0.5.2\n"
        "# Bundled OFL Korean font fallback.\n"
        "init 999 python:\n"
        f"    _rpt_font = {font!r}\n"
        "    try:\n"
        "        gui.language = 'korean-with-spaces'\n"
        "        gui.text_font = _rpt_font\n"
        "        gui.name_text_font = _rpt_font\n"
        "        gui.interface_text_font = _rpt_font\n"
        "        gui.system_font = _rpt_font\n"
        "    except Exception:\n"
        "        pass\n"
        f"    for _rpt_style_name in {styles!r}:\n"
        "        try:\n"
        "            getattr(style, _rpt_style_name).font = _rpt_font\n"
        "        except Exception:\n"
        "            pass\n"
        "    try:\n"
        "        del _rpt_style_name\n"
        "    except Exception:\n"
        "        pass\n"
    )


def ensure_bundled_korean_font(patch_root, target_dir):
    """Put font, license and style override inside the exact applied/shared payload."""
    if target_dir != "korean":
        return None
    font_src = _bundled_path(BUNDLED_FONT_NAME)
    if font_src is None:
        raise RuntimeError("RenPy Tools 기본 한글 폰트가 설치 파일에서 누락되었습니다.")

    patch_root = Path(patch_root)
    font_dir = patch_root / PATCH_FONT_DIR
    font_dir.mkdir(parents=True, exist_ok=True)
    font_dst = font_dir / BUNDLED_FONT_NAME
    shutil.copy2(font_src, font_dst)

    license_src = _bundled_path(BUNDLED_LICENSE_NAME)
    if license_src is not None:
        shutil.copy2(license_src, font_dir / BUNDLED_LICENSE_NAME)

    # This file stays in tl/korean and is therefore also packed into TreeTL.exe.
    # The init priority is late on purpose: it overwrites normal game GUI font
    # choices after they have been defined.
    (patch_root / FONT_OVERRIDE_FILE).write_text(
        _font_override_text(target_dir), encoding="utf-8"
    )
    return font_dst


def write_force_korean_loader(game_dir, target_dir):
    game_dir = Path(game_dir)
    loader = game_dir / "renpytools_language.rpy"
    if target_dir != "korean":
        loader.write_text(
            "# Generated by RenPy Tools v0.5.2\n"
            f"define config.language = {target_dir!r}\n",
            encoding="utf-8",
        )
        return loader

    loader.write_text(
        "# Generated by RenPy Tools v0.5.2\n"
        "# Select Korean before normal game startup; font override lives in tl/korean.\n"
        "define config.language = 'korean'\n",
        encoding="utf-8",
    )
    return loader


def apply_patch_v052(self, patch_root, game_dir, target_dir):
    # Add the font before applying so both the local game and the later
    # standalone distribution EXE receive the same font payload.
    ensure_bundled_korean_font(patch_root, target_dir)
    destination, backup = _PREVIOUS_APPLY(self, patch_root, game_dir, target_dir)
    write_force_korean_loader(game_dir, target_dir)
    return destination, backup


def install_v052_render_compat():
    global _INSTALLED, _PREVIOUS_APPLY
    core.extract_strings = extract_strings_v052
    master_hq.iter_extract_strings_stream = iter_extract_strings_stream_v052
    if not _INSTALLED:
        _PREVIOUS_APPLY = core.PatcherApp.apply_patch_to_game
        core.PatcherApp.apply_patch_to_game = apply_patch_v052
        _INSTALLED = True
    return True


def run_v052_self_test():
    try:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            script = root / "script.rpy"
            script.write_text(
                'label start:\n'
                '    e "Hello"\n'
                '    menu:\n'
                '        "Yes":\n'
                '            pass\n'
                '        "No":\n'
                '            pass\n'
                'define technical = "InternalToken"\n',
                encoding="utf-8",
            )
            values = [text for _, text in extract_strings_v052(script)]
            assert "Hello" in values and "Yes" in values and "No" in values
            assert "InternalToken" not in values

            override = _font_override_text("korean")
            assert "NotoSansKR.ttf" in override
            assert "say_dialogue" in override
            game = root / "game"
            game.mkdir()
            loader = write_force_korean_loader(game, "korean")
            assert "define config.language = 'korean'" in loader.read_text(encoding="utf-8")
        return 0
    except Exception as exc:
        try:
            Path("RenPyTools-v052-selftest-error.txt").write_text(repr(exc), encoding="utf-8")
        except Exception:
            pass
        return 1
