#!/usr/bin/env python3
import shutil
import zipfile
from pathlib import Path

import v051_prepare
from RenPyExtractor import resolve_game_folder
from v052_render_compat import BUNDLED_FONT_NAME, PATCH_FONT_DIR, ensure_bundled_korean_font
from v053_template_tl import augment_patch_from_existing_tl, find_best_translation_template

_ORIGINAL_PREPARE = v051_prepare.prepare_decompiled_source
_INSTALLED = False


def prepare_decompiled_source_strict(source, status=None):
    """Never continue translation after an RPYC/RPYMC decompile failure.

    v0.5.4 still allowed a failed compiled file to fall back to a readable .rpy
    beside it. That made the UI say preparation was complete even though the
    compiled script had not actually been decompiled. v0.5.5 makes the promise
    literal: if compiled scripts are present, every attempted decompile must
    succeed before translation may start.
    """
    prepared, stats = _ORIGINAL_PREPARE(source, status=status)
    failed = int(stats.get("decompile_fail", 0) or 0)
    compiled = int(stats.get("compiled", 0) or 0)
    if compiled and failed:
        try:
            shutil.rmtree(prepared, ignore_errors=True)
        except Exception:
            pass
        raise RuntimeError(
            "RPYC/RPYMC 디컴파일이 완전히 끝나지 않아 번역을 중단했습니다. "
            f"전체 {compiled}개 중 실패 {failed}개입니다. "
            "v0.5.5부터는 디컴파일 실패 상태에서 기존 .rpy로 대신 번역하지 않습니다."
        )
    if compiled and int(stats.get("decompiled", 0) or 0) < compiled:
        # This catches future preparation regressions where a compiled file is
        # silently skipped without being counted as a failure.
        raise RuntimeError(
            "컴파일된 스크립트 일부가 실제 디컴파일되지 않았습니다. "
            f"감지 {compiled}개 / 성공 {int(stats.get('decompiled', 0) or 0)}개. 번역을 중단합니다."
        )
    return prepared, stats


def install_v055_strict_prepare():
    global _INSTALLED
    # prepare_complete_source resolves this module global at call time.
    v051_prepare.prepare_decompiled_source = prepare_decompiled_source_strict
    _INSTALLED = True
    return True


def write_portable_korean_font_loader(patch_root, target_dir):
    """Put font activation inside the payload so shared EXEs behave like local apply."""
    if target_dir != "korean":
        return None
    patch_root = Path(patch_root)
    font = f"tl/{target_dir}/{PATCH_FONT_DIR}/{BUNDLED_FONT_NAME}"
    styles = (
        "default", "say_dialogue", "say_label", "input", "button_text",
        "choice_button_text", "quick_button_text", "navigation_button_text",
        "game_menu_label", "game_menu_navigation_button_text", "pref_label",
        "pref_button_text", "slot_button_text", "file_slot_button_text",
        "confirm_prompt", "confirm_button_text", "notify_text",
    )
    path = patch_root / "renpytools_font_compat.rpy"
    path.write_text(
        "# Generated by RenPy Tools v0.5.5\n"
        "# Portable Korean font layer included in ZIP/EXE/local apply.\n"
        "init 999 python:\n"
        f"    if config.language == {target_dir!r}:\n"
        f"        _rpt_font = {font!r}\n"
        "        try:\n"
        "            gui.language = 'korean-with-spaces'\n"
        "            gui.text_font = _rpt_font\n"
        "            gui.name_text_font = _rpt_font\n"
        "            gui.interface_text_font = _rpt_font\n"
        "            gui.system_font = _rpt_font\n"
        "        except Exception:\n"
        "            pass\n"
        f"        for _rpt_style_name in {styles!r}:\n"
        "            try:\n"
        "                getattr(style, _rpt_style_name).font = _rpt_font\n"
        "            except Exception:\n"
        "                pass\n"
        "\ntranslate korean python:\n"
        f"    _rpt_font = {font!r}\n"
        "    try:\n"
        "        gui.language = 'korean-with-spaces'\n"
        "        gui.text_font = _rpt_font\n"
        "        gui.name_text_font = _rpt_font\n"
        "        gui.interface_text_font = _rpt_font\n"
        "        gui.system_font = _rpt_font\n"
        "    except Exception:\n"
        "        pass\n"
        f"    for _rpt_style_name in {styles!r}:\n"
        "        try:\n"
        "            getattr(style, _rpt_style_name).font = _rpt_font\n"
        "        except Exception:\n"
        "            pass\n",
        encoding="utf-8",
    )
    return path


def resolve_payload_game(owner):
    options = getattr(owner, "job_options", {}) or {}
    direct = options.get("apply_game_path")
    if direct:
        p = Path(direct)
        if p.is_dir() and p.name.lower() == "game":
            return p
    for key in ("history_source_path", "source_path"):
        raw = options.get(key)
        if not raw:
            continue
        try:
            return resolve_game_folder(raw)
        except Exception:
            pass
    return None


def prepare_final_payload(owner, patch_root, target_dir):
    """Finalize the exact payload BEFORE ZIP/standalone EXE/local installation."""
    patch_root = Path(patch_root)
    game_dir = resolve_payload_game(owner)
    template = find_best_translation_template(game_dir, target_dir) if game_dir else None
    structure = None
    if game_dir and template is not None:
        structure = augment_patch_from_existing_tl(patch_root, game_dir, target_dir)
        if structure is None:
            # Do not silently ship the known-bad one-file strings fallback when
            # this game already gives us a valid translation template to mirror.
            raise RuntimeError(
                f"기존 번역 구조(tl/{template.name})를 찾았지만 한국어 구조 변환에 실패했습니다. "
                "renpytools_strings.rpy 하나짜리 패치를 대신 만들지 않고 중단합니다."
            )

    ensure_bundled_korean_font(patch_root, target_dir)
    write_portable_korean_font_loader(patch_root, target_dir)
    return structure


def repack_existing_zip(owner, patch_root):
    """The legacy worker writes ZIP before standalone build; rewrite it after finalization."""
    output = getattr(owner, "output_zip", None)
    if not output:
        return None
    output = Path(output)
    patch_root = Path(patch_root)
    try:
        temp_root = patch_root.parents[2]  # <work>/game/tl/korean -> <work>
    except Exception:
        return None
    if not temp_root.is_dir():
        return None
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED, compresslevel=1) as archive:
        for path in temp_root.rglob("*"):
            if path.is_file():
                archive.write(path, path.relative_to(temp_root))
    return output


def run_v055_self_test():
    try:
        import tempfile
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            patch = root / "game" / "tl" / "korean"
            patch.mkdir(parents=True)
            loader = write_portable_korean_font_loader(patch, "korean")
            text = loader.read_text(encoding="utf-8")
            assert "NotoSansKR.ttf" in text
            assert "translate korean python:" in text
            assert "init 999 python:" in text
            install_v055_strict_prepare()
            assert v051_prepare.prepare_decompiled_source is prepare_decompiled_source_strict
        return 0
    except Exception as exc:
        try:
            Path("RenPyTools-v055-selftest-error.txt").write_text(repr(exc), encoding="utf-8")
        except Exception:
            pass
        return 1
