#!/usr/bin/env python3
from pathlib import Path

import v055_release_payload
from v052_render_compat import BUNDLED_FONT_NAME, PATCH_FONT_DIR


UI_TEXT_STYLES = (
    "default", "text", "say_dialogue", "say_label", "input",
    "button_text", "label_text", "choice_button_text", "quick_button_text",
    "navigation_button_text", "game_menu_label", "game_menu_label_text",
    "game_menu_navigation_button_text", "pref_label", "pref_label_text",
    "pref_button_text", "radio_button_text", "check_button_text",
    "slider_label", "slider_label_text", "page_label", "page_label_text",
    "slot_button_text", "file_slot_button_text", "confirm_prompt",
    "confirm_button_text", "notify_text", "help_button_text",
    "about_label", "about_label_text", "history_name", "history_name_text",
    "history_text", "history_label", "history_label_text", "tooltip",
    "tooltip_text",
)


def _loader_text(target_dir="korean"):
    font = f"tl/{target_dir}/{PATCH_FONT_DIR}/{BUNDLED_FONT_NAME}"
    styles = repr(UI_TEXT_STYLES)
    # Capture fonts already used by the game's GUI and register them as Korean
    # replacements. This also catches custom styles that keep using the same
    # English/Japanese font even when their style name is unknown to us.
    return (
        "# Generated by RenPy Tools v0.5.6\n"
        "# Global Korean UI font compatibility: dialogue, choices, preferences and menus.\n"
        "init 998 python:\n"
        f"    _rpt_korean_font = {font!r}\n"
        f"    _rpt_ui_styles = {styles}\n"
        "    def _rpt_register_font(old_font):\n"
        "        if not isinstance(old_font, str) or not old_font or old_font == _rpt_korean_font:\n"
        "            return\n"
        "        for _rpt_bold in (False, True):\n"
        "            for _rpt_italic in (False, True):\n"
        "                try:\n"
        "                    config.font_replacement_map[old_font, _rpt_bold, _rpt_italic] = (_rpt_korean_font, _rpt_bold, _rpt_italic)\n"
        "                except Exception:\n"
        "                    pass\n"
        "    def _rpt_apply_korean_ui_font():\n"
        "        try:\n"
        "            _rpt_register_font(gui.text_font)\n"
        "            _rpt_register_font(gui.name_text_font)\n"
        "            _rpt_register_font(gui.interface_text_font)\n"
        "            _rpt_register_font(gui.system_font)\n"
        "        except Exception:\n"
        "            pass\n"
        "        for _rpt_style_name in _rpt_ui_styles:\n"
        "            try:\n"
        "                _rpt_style = getattr(style, _rpt_style_name)\n"
        "                _rpt_register_font(_rpt_style.font)\n"
        "                _rpt_style.font = _rpt_korean_font\n"
        "            except Exception:\n"
        "                pass\n"
        "        try:\n"
        "            gui.language = 'korean-with-spaces'\n"
        "            gui.text_font = _rpt_korean_font\n"
        "            gui.name_text_font = _rpt_korean_font\n"
        "            gui.interface_text_font = _rpt_korean_font\n"
        "            gui.system_font = _rpt_korean_font\n"
        "        except Exception:\n"
        "            pass\n"
        "\n"
        "init 999 python:\n"
        f"    if config.language == {target_dir!r}:\n"
        "        _rpt_apply_korean_ui_font()\n"
        "\n"
        "translate korean python:\n"
        "    _rpt_apply_korean_ui_font()\n"
    )


def write_global_korean_font_loader(patch_root, target_dir):
    if target_dir != "korean":
        return None
    patch_root = Path(patch_root)
    path = patch_root / "renpytools_font_compat.rpy"
    path.write_text(_loader_text(target_dir), encoding="utf-8")
    return path


def install_v056_global_ui_font():
    v055_release_payload.write_portable_korean_font_loader = write_global_korean_font_loader
    return True


def run_v056_self_test():
    try:
        import tempfile
        with tempfile.TemporaryDirectory() as td:
            patch = Path(td) / "korean"
            patch.mkdir()
            path = write_global_korean_font_loader(patch, "korean")
            text = path.read_text(encoding="utf-8")
            assert "pref_label_text" in text
            assert "radio_button_text" in text
            assert "check_button_text" in text
            assert "choice_button_text" in text
            assert "font_replacement_map" in text
            assert "gui.interface_text_font" in text
            assert "NotoSansKR.ttf" in text
        return 0
    except Exception as exc:
        try:
            Path("RenPyTools-v056-selftest-error.txt").write_text(repr(exc), encoding="utf-8")
        except Exception:
            pass
        return 1
