#!/usr/bin/env python3
import re
from pathlib import Path

import RenPyToolsLauncherV055 as launcher055
import v055_release_payload
from v052_render_compat import BUNDLED_FONT_NAME, PATCH_FONT_DIR
from v053_template_tl import find_best_translation_template

_ORIGINAL_PREPARE_FINAL = launcher055.prepare_final_payload
_INSTALLED = False

_STYLE_HEADER_RE = re.compile(
    r"(?m)^translate\s+(?P<lang>[A-Za-z_][A-Za-z0-9_]*)\s+style\s+"
    r"(?P<style>[A-Za-z_][A-Za-z0-9_]*)\s*:\s*$"
)
_CHOICE_HINTS = ("choice", "menu", "answer", "select", "option")

# Standard/frequently inherited text styles used by Ren'Py menu choices.
FALLBACK_CHOICE_STYLES = (
    "choice_button_text",
    "button_text",
    "menu_choice_button_text",
    "choice_text",
)


def _translation_style_blocks(text):
    matches = list(_STYLE_HEADER_RE.finditer(text))
    out = []
    for index, match in enumerate(matches):
        # End at the next top-level translate header of any kind, not only style.
        next_match = re.search(r"(?m)^translate\s+[A-Za-z_][A-Za-z0-9_]*\s+", text[match.end():])
        end = match.end() + next_match.start() if next_match else len(text)
        out.append((match, text[match.start():end]))
    return out


def _render_style_block(block, style_name, target_dir, font):
    lines = block.splitlines()
    if not lines:
        return None
    lines[0] = f"translate {target_dir} style {style_name}:"
    body = []
    font_written = False
    for line in lines[1:]:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            body.append(line)
            continue
        if re.match(r"^font\s+", stripped):
            indent = line[: len(line) - len(line.lstrip())] or "    "
            body.append(f'{indent}font "{font}"')
            font_written = True
        else:
            body.append(line)
    if not font_written:
        body.append(f'    font "{font}"')
    return "\n".join([lines[0]] + body).rstrip() + "\n"


def write_choice_compat(patch_root, game_dir, target_dir="korean"):
    if target_dir != "korean":
        return None
    patch_root = Path(patch_root)
    font = f"tl/{target_dir}/{PATCH_FONT_DIR}/{BUNDLED_FONT_NAME}"

    custom_blocks = []
    seen_styles = set()
    template = find_best_translation_template(game_dir, target_dir) if game_dir else None
    if template is not None:
        for script in sorted(Path(template).rglob("*.rpy")):
            try:
                text = script.read_text(encoding="utf-8", errors="replace")
            except Exception:
                continue
            for match, block in _translation_style_blocks(text):
                style_name = match.group("style")
                low = style_name.lower()
                if not any(hint in low for hint in _CHOICE_HINTS):
                    continue
                rendered = _render_style_block(block, style_name, target_dir, font)
                if rendered and style_name not in seen_styles:
                    custom_blocks.append(rendered)
                    seen_styles.add(style_name)

    for style_name in FALLBACK_CHOICE_STYLES:
        if style_name in seen_styles:
            continue
        custom_blocks.append(
            f"translate {target_dir} style {style_name}:\n"
            f'    font "{font}"\n'
        )
        seen_styles.add(style_name)

    # Language-time Python assignment catches projects that configure choice
    # fonts through gui variables instead of style statements.
    python_block = (
        f"translate {target_dir} python:\n"
        f"    _rpt_choice_font = {font!r}\n"
        "    for _rpt_attr in ('choice_button_text_font', 'button_text_font', 'interface_text_font'):\n"
        "        try:\n"
        "            if hasattr(gui, _rpt_attr):\n"
        "                setattr(gui, _rpt_attr, _rpt_choice_font)\n"
        "        except Exception:\n"
        "            pass\n"
    )

    path = patch_root / "renpytools_choice_compat.rpy"
    path.write_text(
        "# Generated by RenPy Tools v0.5.7\n"
        "# Choice-screen-specific Korean font compatibility.\n\n"
        + "\n".join(custom_blocks)
        + "\n"
        + python_block,
        encoding="utf-8",
    )
    return {
        "path": str(path),
        "template": str(template) if template else None,
        "styles": sorted(seen_styles),
    }


def prepare_final_payload_v057(owner, patch_root, target_dir):
    structure = _ORIGINAL_PREPARE_FINAL(owner, patch_root, target_dir)
    game_dir = v055_release_payload.resolve_payload_game(owner)
    result = write_choice_compat(patch_root, game_dir, target_dir)
    if result and hasattr(owner, "add_log"):
        try:
            owner.add_log(f"[선택지 한글 폰트] 언어별 스타일 {len(result['styles'])}개 보강")
        except Exception:
            pass
    return structure


def install_v057_choice_compat():
    global _INSTALLED
    launcher055.prepare_final_payload = prepare_final_payload_v057
    _INSTALLED = True
    return True


def run_v057_self_test():
    try:
        import tempfile
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            game = root / "game"
            japanese = game / "tl" / "japanese"
            japanese.mkdir(parents=True)
            (japanese / "screens.rpy").write_text(
                'translate japanese style custom_choice_button_text:\n'
                '    font "JapaneseOnly.ttf"\n'
                '    size 31\n\n',
                encoding="utf-8",
            )
            patch = root / "patch"
            patch.mkdir()
            result = write_choice_compat(patch, game, "korean")
            text = (patch / "renpytools_choice_compat.rpy").read_text(encoding="utf-8")
            assert result
            assert "translate korean style custom_choice_button_text:" in text
            assert "JapaneseOnly.ttf" not in text
            assert "NotoSansKR.ttf" in text
            assert "translate korean style choice_button_text:" in text
            assert "choice_button_text_font" in text
        return 0
    except Exception as exc:
        try:
            Path("RenPyTools-v057-selftest-error.txt").write_text(repr(exc), encoding="utf-8")
        except Exception:
            pass
        return 1
