from pathlib import Path

path = Path("RenPyAIPatcher.py")
s = path.read_text(encoding="utf-8")


def replace_once(old, new, label):
    global s
    if old not in s:
        raise SystemExit(f"Missing patch target: {label}")
    s = s.replace(old, new, 1)


replace_once("import shutil\nimport threading", "import shutil\nimport sys\nimport threading", "sys import")
replace_once('VERSION = "0.2.9"', 'VERSION = "0.3.0"', "version")
replace_once(
    "Ren'Py AI 한글패치 제작 · 배치 번역 · 기록/이어하기 · 자동 패치 적용",
    "Ren'Py AI 한글패치 제작 · 중복 안전 패치 · 독립 실행 EXE · 자동 적용",
    "subtitle",
)
replace_once(
    "        self.backup_path = None\n        self.container = ttk.Frame",
    "        self.backup_path = None\n        self.standalone_path = None\n        self.container = ttk.Frame",
    "standalone state",
)

old_apply = '''    def apply_patch_to_game(self, patch_root, game_dir, target_dir):
        game_dir = Path(game_dir)
        if game_dir.name.lower() != "game" or not game_dir.is_dir():
            raise RuntimeError("자동 적용 대상 game 폴더를 찾지 못했습니다.")
        destination = game_dir / "tl" / target_dir
        backup = None
        if destination.exists() and any(destination.rglob("*")):
            stamp = time.strftime("%Y%m%d_%H%M%S")
            backup = game_dir / "tl" / "_RenPyTools_Backup" / f"{target_dir}_{stamp}"
            backup.parent.mkdir(parents=True, exist_ok=True)
            shutil.copytree(destination, backup)
        destination.mkdir(parents=True, exist_ok=True)
        shutil.copytree(patch_root, destination, dirs_exist_ok=True)
        return destination, backup
'''

new_apply = '''    def apply_patch_to_game(self, patch_root, game_dir, target_dir):
        game_dir = Path(game_dir)
        if game_dir.name.lower() != "game" or not game_dir.is_dir():
            raise RuntimeError("자동 적용 대상 game 폴더를 찾지 못했습니다.")
        destination = game_dir / "tl" / target_dir
        backup = None
        if destination.exists() and any(destination.rglob("*")):
            stamp = time.strftime("%Y%m%d_%H%M%S")
            backup = game_dir / "_RenPyTools_Backup" / f"{target_dir}_{stamp}"
            backup.parent.mkdir(parents=True, exist_ok=True)
            shutil.copytree(destination, backup)
            # Older RenPy Tools versions generated many per-file translation files.
            # Remove them after backup so stale duplicate `old` strings cannot remain.
            shutil.rmtree(destination)
        destination.mkdir(parents=True, exist_ok=True)
        shutil.copytree(patch_root, destination, dirs_exist_ok=True)
        return destination, backup

    def build_standalone_patch(self, patch_root, target_dir):
        """Create one shareable EXE containing the patch payload."""
        candidates = [
            Path(sys.executable).resolve().with_name("RenPyPatchInstallerStub.exe"),
            Path(__file__).resolve().with_name("RenPyPatchInstallerStub.exe"),
        ]
        stub = next((p for p in candidates if p.is_file()), None)
        if stub is None:
            raise RuntimeError("독립 패치 설치기 파일(RenPyPatchInstallerStub.exe)을 찾지 못했습니다.")

        files = sorted(p for p in Path(patch_root).rglob("*") if p.is_file())
        if not files:
            raise RuntimeError("독립 패치에 넣을 번역 파일이 없습니다.")

        archive = bytearray(b"RPTPKG01")
        archive += len(files).to_bytes(4, "little")
        lang = target_dir.encode("utf-8")
        archive += len(lang).to_bytes(2, "little")
        archive += lang

        for file in files:
            rel = file.relative_to(patch_root).as_posix().encode("utf-8")
            data = file.read_bytes()
            archive += len(rel).to_bytes(4, "little")
            archive += len(data).to_bytes(8, "little")
            archive += rel
            archive += data

        output = self.output_zip.with_name(self.output_zip.stem + "_Standalone.exe")
        shutil.copy2(stub, output)
        with output.open("ab") as fp:
            fp.write(archive)
            fp.write(len(archive).to_bytes(8, "little"))
            fp.write(b"RPTEND01")
        return output
'''
replace_once(old_apply, new_apply, "apply/standalone methods")

old_generation = '''            final_failed = [src for src in sources if src not in memory]
            grouped = {}
            for f, no, src in items:
                grouped.setdefault(f, []).append((no, src, memory.get(src, src)))
            for f, entries in grouped.items():
                rel = f.relative_to(game)
                dest = patch_root / rel
                dest.parent.mkdir(parents=True, exist_ok=True)
                lines = ["# Generated by RenPy AI Patcher", f"translate {target_dir} strings:", ""]
                for no, old, new in entries:
                    lines.extend([f"    # {rel.as_posix()}:{no}", f'    old "{escape_rpy(old)}"', f'    new "{escape_rpy(new)}"', ""])
                dest.write_text("\\n".join(lines), encoding="utf-8")
'''

new_generation = '''            final_failed = [src for src in sources if src not in memory]
            # Ren'Py rejects the same `old` value if it is registered in multiple
            # translate-strings blocks. `sources` is game-wide deduplicated, so
            # v0.3.0 writes exactly one translation block and one entry per old text.
            dest = patch_root / "renpytools_strings.rpy"
            lines = [
                "# Generated by RenPy AI Patcher v0.3.0",
                "# Game-wide unique strings; duplicate old values are removed.",
                f"translate {target_dir} strings:",
                "",
            ]
            for old in sources:
                new = memory.get(old, old)
                lines.extend([f'    old "{escape_rpy(old)}"', f'    new "{escape_rpy(new)}"', ""])
            dest.write_text("\\n".join(lines), encoding="utf-8")
'''
replace_once(old_generation, new_generation, "duplicate-safe generation")

old_after_zip = '''            with zipfile.ZipFile(self.output_zip, "w", zipfile.ZIP_DEFLATED, compresslevel=1) as archive:
                for path in temp.rglob("*"):
                    if path.is_file():
                        archive.write(path, path.relative_to(temp))

            self.applied_path = None
'''

new_after_zip = '''            with zipfile.ZipFile(self.output_zip, "w", zipfile.ZIP_DEFLATED, compresslevel=1) as archive:
                for path in temp.rglob("*"):
                    if path.is_file():
                        archive.write(path, path.relative_to(temp))

            self.standalone_path = None
            if final_failed:
                self.add_log(f"[독립 EXE 보류] 미번역 {len(final_failed)}개가 남아 설치 EXE를 만들지 않았습니다.")
            else:
                try:
                    self.progress(1, 1, "공유용 독립 패치 EXE 생성 중...")
                    self.standalone_path = self.build_standalone_patch(patch_root, target_dir)
                    self.add_log(f"[독립 EXE 생성] {self.standalone_path}")
                except Exception as exc:
                    # Keep the ZIP/auto-apply result even if only EXE packaging fails.
                    self.add_log(f"[독립 EXE 생성 실패] {exc}")

            self.applied_path = None
'''
replace_once(old_after_zip, new_after_zip, "standalone generation call")

old_done = '''        ttk.Label(body, text=str(self.output_zip), style="Muted.Card.TLabel").pack(anchor="center")
        if self.applied_path:
'''
new_done = '''        ttk.Label(body, text=str(self.output_zip), style="Muted.Card.TLabel").pack(anchor="center")
        if self.standalone_path:
            ttk.Label(body, text="✓ 공유용 단일 패치 EXE 생성 완료", style="Muted.Card.TLabel").pack(anchor="center", pady=(8, 0))
            ttk.Label(body, text=str(self.standalone_path), style="Muted.Card.TLabel").pack(anchor="center", pady=(2, 0))
        if self.applied_path:
'''
replace_once(old_done, new_done, "done page standalone")

path.write_text(s, encoding="utf-8")
print("RenPyAIPatcher.py upgraded to v0.3.0")
