from pathlib import Path

p = Path('RenPyAIPatcher.py')
s = p.read_text(encoding='utf-8')

repls = []

def rep(old, new, count=1):
    global s
    found = s.count(old)
    if found < count:
        raise SystemExit(f'Expected at least {count} occurrences, found {found}: {old[:100]!r}')
    s = s.replace(old, new, count)

rep('VERSION = "0.3.1"', 'VERSION = "0.3.2"')
rep("Ren'Py AI 한글패치 제작 · 무료 번역 엔진 · 429 자동 우회 · 자동 패치", "Ren'Py AI 한글패치 제작 · 무료 번역 엔진 · 언어 자동 활성화 · 자동 패치")

old_apply = '''    def apply_patch_to_game(self, patch_root, game_dir, target_dir):
        game_dir = Path(game_dir)
        if game_dir.name.lower() != "game" or not game_dir.is_dir():
            raise RuntimeError("자동 적용 대상 game 폴더를 찾지 못했습니다.")
        destination = game_dir / "tl" / target_dir
        backup = None
        if destination.exists() and any(destination.rglob("*")):
            stamp = time.strftime("%Y%m%d_%H%M%S")
            backup = game_dir / "_RenPyTools_Backup" / f"{target_dir}_{stamp}"
            backup.parent.mkdir(parents=True, exist_ok=True)
            shutil.copytree(destination, backup)
            # Older RenPy Tools versions generated many per-file translation files.
            # Remove them after backup so stale duplicate `old` strings cannot remain.
            shutil.rmtree(destination)
        destination.mkdir(parents=True, exist_ok=True)
        shutil.copytree(patch_root, destination, dirs_exist_ok=True)
        return destination, backup
'''
new_apply = '''    def apply_patch_to_game(self, patch_root, game_dir, target_dir):
        game_dir = Path(game_dir)
        if game_dir.name.lower() != "game" or not game_dir.is_dir():
            raise RuntimeError("자동 적용 대상 game 폴더를 찾지 못했습니다.")
        destination = game_dir / "tl" / target_dir
        backup = None
        stamp = time.strftime("%Y%m%d_%H%M%S")
        backup_base = game_dir / "_RenPyTools_Backup"
        if destination.exists() and any(destination.rglob("*")):
            backup = backup_base / f"{target_dir}_{stamp}"
            backup.parent.mkdir(parents=True, exist_ok=True)
            shutil.copytree(destination, backup)
            # Older RenPy Tools versions generated many per-file translation files.
            # Remove them after backup so stale duplicate `old` strings cannot remain.
            shutil.rmtree(destination)
        destination.mkdir(parents=True, exist_ok=True)
        shutil.copytree(patch_root, destination, dirs_exist_ok=True)

        # Ren'Py keeps the original game language as `None` when a game has no
        # language selector. In that state tl/<language> string translations are
        # present on disk but are not active. Install a tiny root-level loader so
        # the generated translation is actually selected at game startup.
        language_loader = game_dir / "renpytools_language.rpy"
        if language_loader.exists():
            backup_base.mkdir(parents=True, exist_ok=True)
            loader_backup = backup_base / f"renpytools_language_{stamp}.rpy"
            shutil.copy2(language_loader, loader_backup)
        language_loader.write_text(
            "# Generated by RenPy Tools v0.3.2\\n"
            "# Activates the language installed by RenPy Tools.\\n"
            "init 999 python:\\n"
            f"    config.language = {target_dir!r}\\n",
            encoding="utf-8",
        )
        return destination, backup
'''
rep(old_apply, new_apply)

old_patch_start = '''            # Ren'Py rejects the same `old` value if it is registered in multiple
            # translate-strings blocks. `sources` is game-wide deduplicated, so
            # v0.3.0 writes exactly one translation block and one entry per old text.
            dest = patch_root / "renpytools_strings.rpy"
            lines = [
                "# Generated by RenPy AI Patcher v0.3.0",
'''
new_patch_start = '''            # Ren'Py rejects the same `old` value if it is registered in multiple
            # translate-strings blocks. `sources` is game-wide deduplicated, so
            # v0.3.2 writes exactly one translation block and one entry per old text.
            dest = patch_root / "renpytools_strings.rpy"
            lines = [
                "# Generated by RenPy AI Patcher v0.3.2",
'''
rep(old_patch_start, new_patch_start)

old_after_dest = '''            dest.write_text("\\n".join(lines), encoding="utf-8")
            (temp / "패치_설명.txt").write_text(
                f"번역 파일: game/tl/{target_dir}/\\n최종 미번역: {len(final_failed)}개\\n"
'''
new_after_dest = '''            dest.write_text("\\n".join(lines), encoding="utf-8")

            # This file lives directly under game/, not tl/. It forces the target
            # language on games that do not expose a language selector themselves.
            language_loader = temp / "game" / "renpytools_language.rpy"
            language_loader.write_text(
                "# Generated by RenPy Tools v0.3.2\\n"
                "# Activates the language installed by RenPy Tools.\\n"
                "init 999 python:\\n"
                f"    config.language = {target_dir!r}\\n",
                encoding="utf-8",
            )

            (temp / "패치_설명.txt").write_text(
                f"번역 파일: game/tl/{target_dir}/\\n언어 활성화: game/renpytools_language.rpy\\n최종 미번역: {len(final_failed)}개\\n"
'''
rep(old_after_dest, new_after_dest)

p.write_text(s, encoding='utf-8')

iss = Path('installer.iss')
i = iss.read_text(encoding='utf-8')
if '#define MyAppVersion "0.3.1"' not in i:
    raise SystemExit('installer.iss is not v0.3.1')
i = i.replace('#define MyAppVersion "0.3.1"', '#define MyAppVersion "0.3.2"', 1)
i = i.replace('; v0.3.0 adds duplicate-safe translation output and standalone patch EXE creation.', '; v0.3.2 activates generated translations automatically and keeps standalone patch support.')
iss.write_text(i, encoding='utf-8')

cpp = Path('RenPyPatchInstallerStub.cpp')
c = cpp.read_text(encoding='utf-8')
needle = '''    for (const auto& pf : files) {
        fs::path rel = fs::path(widen_utf8(pf.relative_path));
        if (!safe_relative(rel)) {
            error = L"안전하지 않은 패치 경로가 포함되어 있습니다.";
            return false;
        }

        fs::path dest = target / rel;
        ec.clear();
        fs::create_directories(dest.parent_path(), ec);
        if (ec) {
            error = L"패치 하위 폴더 생성에 실패했습니다.\\n" + widen_utf8(ec.message());
            return false;
        }

        std::ofstream out(dest, std::ios::binary | std::ios::trunc);
        if (!out) {
            error = L"패치 파일을 쓸 수 없습니다: " + dest.wstring();
            return false;
        }
        if (!pf.data.empty()) out.write(pf.data.data(), static_cast<std::streamsize>(pf.data.size()));
        if (!out.good()) {
            error = L"패치 파일 쓰기에 실패했습니다: " + dest.wstring();
            return false;
        }
    }
    return true;
'''
replacement = '''    for (const auto& pf : files) {
        fs::path rel = fs::path(widen_utf8(pf.relative_path));
        if (!safe_relative(rel)) {
            error = L"안전하지 않은 패치 경로가 포함되어 있습니다.";
            return false;
        }

        fs::path dest = target / rel;
        ec.clear();
        fs::create_directories(dest.parent_path(), ec);
        if (ec) {
            error = L"패치 하위 폴더 생성에 실패했습니다.\\n" + widen_utf8(ec.message());
            return false;
        }

        std::ofstream out(dest, std::ios::binary | std::ios::trunc);
        if (!out) {
            error = L"패치 파일을 쓸 수 없습니다: " + dest.wstring();
            return false;
        }
        if (!pf.data.empty()) out.write(pf.data.data(), static_cast<std::streamsize>(pf.data.size()));
        if (!out.good()) {
            error = L"패치 파일 쓰기에 실패했습니다: " + dest.wstring();
            return false;
        }
    }

    // Activate the installed translation even when the original game has no
    // language selection UI. The file is deliberately outside tl/ so deferred
    // translation loading cannot prevent it from running.
    fs::path loader = game / L"renpytools_language.rpy";
    if (fs::exists(loader, ec)) {
        fs::path backup_base = game / L"_RenPyTools_Backup";
        ec.clear();
        fs::create_directories(backup_base, ec);
        if (!ec) {
            fs::path loader_backup = backup_base / (L"renpytools_language_" + timestamp_now() + L".rpy");
            std::error_code copy_ec;
            fs::copy_file(loader, loader_backup, fs::copy_options::overwrite_existing, copy_ec);
        }
    }

    std::ofstream loader_out(loader, std::ios::binary | std::ios::trunc);
    if (!loader_out) {
        error = L"번역 언어 활성화 파일을 쓸 수 없습니다.";
        return false;
    }
    loader_out << "# Generated by RenPy Tools v0.3.2\\n";
    loader_out << "# Activates the language installed by RenPy Tools.\\n";
    loader_out << "init 999 python:\\n";
    loader_out << "    config.language = '" << lang_dir_utf8 << "'\\n";
    if (!loader_out.good()) {
        error = L"번역 언어 활성화 파일 쓰기에 실패했습니다.";
        return false;
    }
    return true;
'''
if needle not in c:
    raise SystemExit('Could not find standalone apply block')
c = c.replace(needle, replacement, 1)
cpp.write_text(c, encoding='utf-8')

print('Applied RenPy Tools v0.3.2 language activation hotfix')
