from pathlib import Path

p = Path('RenPyAIPatcher.py')
s = p.read_text(encoding='utf-8')

s = s.replace('VERSION = "0.3.4"', 'VERSION = "0.3.5"', 1)

old_instances = '''    LINGVA_INSTANCES = [\n        "https://lingva.ml",\n        "https://translate.plausibility.cloud",\n        "https://translate.projectsegfau.lt",\n    ]'''
new_instances = '''    LINGVA_INSTANCES = [\n        "https://translate.alefvanoon.xyz",\n        "https://translate.dr460nf1r3.org",\n        "https://lingva.garudalinux.org",\n        "https://translate.jae.fi",\n        "https://lingva.ml",\n    ]'''
if old_instances not in s:
    raise SystemExit('old Lingva instance block not found')
s = s.replace(old_instances, new_instances, 1)

marker = '''def make_batches(texts, max_items=BATCH_SIZE, max_chars=BATCH_CHAR_LIMIT):\n    batches, current, chars = [], [], 0\n    for text in texts:\n        cost = len(text) + 32\n        if current and (len(current) >= max_items or chars + cost > max_chars):\n            batches.append(current)\n            current, chars = [], 0\n        current.append(text)\n        chars += cost\n    if current:\n        batches.append(current)\n    return batches\n'''
insert = marker + '''\n\ndef detect_source_code(texts):\n    \"\"\"Best-effort script detection used only to unlock free fallbacks.\n\n    We intentionally detect only scripts that are reliable without a model.\n    Latin languages stay as auto because English/Spanish/French/German cannot\n    be distinguished safely with character ranges alone.\n    \"\"\"\n    sample = \"\\n\".join(list(texts)[:120])[:20000]\n    if not sample:\n        return None\n    hangul = len(re.findall(r'[\\uac00-\\ud7a3]', sample))\n    kana = len(re.findall(r'[\\u3040-\\u30ff]', sample))\n    han = len(re.findall(r'[\\u3400-\\u4dbf\\u4e00-\\u9fff]', sample))\n    if kana >= 2:\n        return 'ja'\n    if hangul >= 2:\n        return 'ko'\n    if han >= 4:\n        return 'zh-CN'\n    return None\n'''
if marker not in s:
    raise SystemExit('make_batches marker not found')
s = s.replace(marker, insert, 1)

old_sources = '''            sources = list(dict.fromkeys(text for _, _, text in items))\n            total = len(sources)\n            memory, failures = self.load_saved_memory(o)'''
new_sources = '''            sources = list(dict.fromkeys(text for _, _, text in items))\n            total = len(sources)\n            if translator.source == "auto":\n                detected_source = detect_source_code(sources)\n                if detected_source:\n                    translator.source = detected_source\n                    self.add_log(f"[원본 언어 자동 판별] {detected_source} · 무료 우회 엔진에서도 사용합니다.")\n            memory, failures = self.load_saved_memory(o)'''
if old_sources not in s:
    raise SystemExit('worker sources block not found')
s = s.replace(old_sources, new_sources, 1)

s = s.replace('Generated by RenPy Tools v0.3.4', 'Generated by RenPy Tools v0.3.5')
s = s.replace('Generated by RenPy AI Patcher v0.3.4', 'Generated by RenPy AI Patcher v0.3.5')
s = s.replace('v0.3.4 writes exactly one translation block', 'v0.3.5 writes exactly one translation block')

p.write_text(s, encoding='utf-8')

iss = Path('installer.iss')
t = iss.read_text(encoding='utf-8')
t = t.replace('#define MyAppVersion "0.3.4"', '#define MyAppVersion "0.3.5"', 1)
iss.write_text(t, encoding='utf-8')
